import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "E-commerce backend",
  description: "Generated by create next app",
};

const Rootlayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>{children}</body> 
    </html>
  );
};

export default Rootlayout;
